export const isAuthenticated = ({ accountName }) => !!accountName;
export const accountName = ({ accountName }) => accountName;
export const evmAddress = ({ evmAddress }) => evmAddress;
export const evmBalance = ({ evmBalance }) => evmBalance;
export const loading = ({ loading }) => loading;
export const isAutoLoading = ({ autoLogin }) => autoLogin;
export const isJustViewer = ({ justViewer }) => justViewer;
export const hasProfile = ({ profiles, accountName }) => profiles.hasOwnProperty(accountName);
export const myProfile = ({ profiles, accountName }) => profiles[accountName];
export const profiles = ({ profiles }) => profiles;
export const data = ({ data }) => data;
