[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.environment]
  NETWORK = "testnet"

[build]
  publish = "dist/spa"
  command = "quasar build"

[build.environment]
  NODE_VERSION = "20.19.0"
