export default () => ({
    footerHeight: 50,
    minSpace: 60,
    maxSpace: 140,
    suggestTokens: [
        { contract: 'eosio.token', sym: 'tlos' },
    ],
    supportTokens: [
        'tlos',
        'seeds',
        'qbe',
        'teach',
        'dric',
        'gem',
        'ezar',
        'sqrl',
        'tlosdac',
        'sand',
        'heart',
        'kanda',
        'ynt',
        'cnt',
        'viita',
        'viict',
        'acorn',
        'robo',
        'word',
        'eosp',
        'legend',
        'people',
        'steemp',
        'nfd',
        'ggwp',
        'date',
        'golos',
        'btcp',
        'ecoin',
    ],
    pTokens: ['tlos'],
    pTokenNetworks: {
        tlos: {
            telos: 'Telos',
            tevm: 'Telos EVM',
        },
    },
});
